; This is linkit configuration file
; For options please refer to documentation
[main]
data_filename   = dcl_rnd_10v_h1_k2001_nplc10_soak8s_comp_samples-3_jun2026.dsv ; # Filename for DSV input
data_filename2  = dcl_rnd_10v_h1_k2001_nplc10_soak8s_comp_samples-3_jun2026.dsv ; # Filename for DSV input
reference_value  = 12
reference_value2 = 21
plot_w = 4800 ; # Width, px
plot_h = 3200  ; # Height, px
plot_w_s = 3600 ; # Width, px
plot_h_s = 2000  ; # Height, px
baseline_ref_column = 1 ;  # Column used as baseline 0.0 ppm reference. Column 0 is date.
dataset_name1 =  xDevs.com HP 3458B
dataset_name2 =  xDevs.com HP 3459X (Twin ADR1000)
dataset_name3 =  xDevs.com HP 3458A stock
dataset_name4 =  xDevs.com Keithley 2002LTC
dataset_name5 =  xDevs.com Datron 1281
dataset_name6 =  xDevs.com HP 34420A CH1
dataset_name7 =  xDevs.com HP 34401A
dataset_name8 =  Keithley 2001 A08 fw (broken)
dataset_name9 =  Keithley 2001M B16 fw (1067777)
dataset_name10 =  1 SD
dataset_name11 =  8508A (peak)
dataset_name12 =  K182-M (peak)

[plot]
chart_title    = INL DC voltage from -10.999 to +10.999 V randoms, 21 Vrng, 15 second soak time, NPLC 10 ;Name for the chart
y_max =   0.5 ;                                                                 # Maximum value for Y axis
y_min =  -0.5 ;                                                                 # Minimum value for Y axis
y_resolution = 0.05 ;                                                         # Y axis ticks resolution
y_label = INL error ;
x_max =  11.0005 ;                                                                 # Maximum value for X axis
x_min = -11.0005 ;                                                                 # Minimum value for X axis
x_resolution = 1.00001 ;                                                        # X axis ticks resolution
x_label = Voltage, V DC ;
dataset_color1 =  #8817BB ;
dataset_color2 =  #FF3302 ;
dataset_color3 =  #006403 ;
dataset_color4 =  #e53338 ;
dataset_color5 =  #ff3300 ;
dataset_color6 =  #c56ac1 ;
dataset_color7 =  #ff0000 ;
dataset_color8 =  #ffcc22 ;
dataset_color9 =  #0000ff ;
dataset_color10 = #ff0000 ;
dataset_color11 = #ffcc22 ;
dataset_color12 = #0000ff ;
run_zcal_mfc   = true ;true to Run 5700 Zero CAL before perf-test)
